//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage50Connector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage50Connector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization to use {0} has not been granted, please see your Peachtree 
        ///	
        ///istrator. {1}    Current status: {2}.
        /// </summary>
        internal static string ACCESS_NOT_GRANTED {
            get {
                return ResourceManager.GetString("ACCESS_NOT_GRANTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sage Peachtree SDK.
        /// </summary>
        internal static string ADDIN_TITLE {
            get {
                return ResourceManager.GetString("ADDIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to j6hHxkAHH31dLcZj3pr7KkJ97ZHBVp3A+yzPcdoPk0dWuW+npaRCig==qkaYdrdCJQAbSJSUCKFY3gdJByefMBYnYWKkyQP+QgvJKev4vbTCsMyaQM3SIy/g8coNs7zcZA8fzCqEbmclgtNp4AefrnrE+fOkJ+EPGJFgSwzZ019vNkKU79dMEWLQPSSm8KpqAspRKJrtxzoRfCW/KB2MlfgTe7i2vskOFM0wpA8RSXgXvBi/gOpnFX0o3ECrO0fEVN681li4DaIeITl3mjdMZazERXvWpibPxwM=.
        /// </summary>
        internal static string APIKEY {
            get {
                return ResourceManager.GetString("APIKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested company is in single user mode and cannot be accessed at this time..
        /// </summary>
        internal static string OpenCompany_CompanyLocked {
            get {
                return ResourceManager.GetString("OpenCompany_CompanyLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sage 50 API is corruped..
        /// </summary>
        internal static string OpenCompany_CorruptedOrTampered {
            get {
                return ResourceManager.GetString("OpenCompany_CorruptedOrTampered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sage 50 has denied access to this application in the requested company..
        /// </summary>
        internal static string OpenCompany_Denied {
            get {
                return ResourceManager.GetString("OpenCompany_Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login has been restricted by the administrator..
        /// </summary>
        internal static string OpenCompany_LoginRestricted {
            get {
                return ResourceManager.GetString("OpenCompany_LoginRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is waiting for authorization from Sage 50 Accounting.  Please launch the Sage 50 application, open the company you wish to access, allow access, then retry..
        /// </summary>
        internal static string OpenCompany_Pending {
            get {
                return ResourceManager.GetString("OpenCompany_Pending", resourceCulture);
            }
        }
    }
}
